version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

exclude_patterns = [
  "migrations/**",
  "**/examples/**",
  "**/env/**"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["requirements.txt"]

  [analyzers.meta]
  runtime_version = "3.x.x"
  type_checker = "mypy"
  max_line_length = 88
  skip_doc_coverage = ["module", "magic", "init"]

[[analyzers]]
name = "test-coverage"
enabled = true
